// <auto-generated />
using System;
using Crud.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crud.EF.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20230208221144_data3")]
    partial class data3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crud.domain.Model.HistoriaProduktow", b =>
                {
                    b.Property<int>("IdZmiany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZmiany"));

                    b.Property<DateTime>("DataZmiany")
                        .HasColumnType("datetime2");

                    b.Property<string>("Produkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaryKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZmiany");

                    b.ToTable("HistoriaProduktow");
                });

            modelBuilder.Entity("Crud.domain.Model.ListaProduktow", b =>
                {
                    b.Property<int>("IdProduktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduktu"));

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscZmian")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduktu");

                    b.ToTable("ListaProduktow");
                });
#pragma warning restore 612, 618
        }
    }
}
